# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-07 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('cmsplugin_articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepluginmodel',
            name='thumbnail_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.ThumbnailOption', verbose_name='thumbnail option'),
        ),
        migrations.AddField(
            model_name='sectionpluginmodel',
            name='thumbnail_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.ThumbnailOption', verbose_name='thumbnail option'),
        ),
    ]
