# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_articles', '0004_auto_20171213_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepluginmodel',
            name='alignment',
        ),
        migrations.RemoveField(
            model_name='articlepluginmodel',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='articlepluginmodel',
            name='thumbnail_option',
        ),
        migrations.RemoveField(
            model_name='sectionpluginmodel',
            name='alignment',
        ),
        migrations.RemoveField(
            model_name='sectionpluginmodel',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='sectionpluginmodel',
            name='thumbnail_option',
        ),
    ]
