# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import djangocms_attributes_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_articles', '0005_auto_20180222_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepluginmodel',
            name='attributes',
            field=djangocms_attributes_field.fields.AttributesField(blank=True, default=dict, verbose_name='Attributes'),
        ),
        migrations.AddField(
            model_name='articlepluginmodel',
            name='template',
            field=models.CharField(choices=[('default', 'Default')], default='default', max_length=255, verbose_name='Template'),
        ),
        migrations.AddField(
            model_name='sectionpluginmodel',
            name='attributes',
            field=djangocms_attributes_field.fields.AttributesField(blank=True, default=dict, verbose_name='Attributes'),
        ),
        migrations.AddField(
            model_name='sectionpluginmodel',
            name='template',
            field=models.CharField(choices=[('default', 'Default')], default='default', max_length=255, verbose_name='Template'),
        ),
    ]
