# Generated by Django 2.2.12 on 2020-04-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_articles', '0006_auto_20180222_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepluginmodel',
            name='header_alignment',
            field=models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center')], max_length=10, verbose_name='Header alignment'),
        ),
        migrations.AlterField(
            model_name='articlepluginmodel',
            name='heading_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'H1'), (2, 'H2'), (3, 'H3'), (4, 'H4'), (5, 'H5'), (6, 'H6')], default=2, help_text='Choose a heading level', verbose_name='Heading level'),
        ),
        migrations.AlterField(
            model_name='articlepluginmodel',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=400, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='articlepluginmodel',
            name='title',
            field=models.CharField(blank=True, default='', max_length=400, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='sectionpluginmodel',
            name='header_alignment',
            field=models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center')], max_length=10, verbose_name='Header alignment'),
        ),
        migrations.AlterField(
            model_name='sectionpluginmodel',
            name='heading_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'H1'), (2, 'H2'), (3, 'H3'), (4, 'H4'), (5, 'H5'), (6, 'H6')], default=2, help_text='Choose a heading level', verbose_name='Heading level'),
        ),
        migrations.AlterField(
            model_name='sectionpluginmodel',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=400, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='sectionpluginmodel',
            name='title',
            field=models.CharField(blank=True, default='', max_length=400, verbose_name='Title'),
        ),
    ]
